[package]
name = "shuttle-service"
version = "0.5.1"
edition = "2021"
license = "Apache-2.0"
description = "Service traits and macros to deploy on the shuttle platform (https://www.shuttle.rs/)"

[lib]
doctest = false

[dependencies]
anyhow = "1.0.62"
async-trait = "0.1.57"
axum = { version = "0.5.15", optional = true }
cargo = { version = "0.64.0", optional = true }
chrono = "0.4.22"
frenezulo_beta = { version = "0.1.0", optional = true }
futures = { version = "0.3.23", features = ["std"] }
hyper = { version = "0.14.20", features = ["server", "tcp", "http1"], optional = true }
lazy_static = "1.4.0"
libloading = { version = "0.7.3", optional = true }
log = "0.4.17"
mongodb = { version = "2.3.0", optional = true }
paste = "1.0.8"
poem = { version = "1.3.40", optional = true }
regex = "1.6.0"
rocket = { version = "0.5.0-rc.2", optional = true }
serenity = { version = "0.11.5", default-features = false, features = ["client", "gateway", "rustls_backend", "model"], optional = true }
sqlx = { version = "0.6.1", optional = true }
sync_wrapper = { version = "0.1.1", optional = true }
thiserror = "1.0.32"
tide = { version = "0.16.0", optional = true }
tokio = { version = "1.20.1", features = ["rt", "rt-multi-thread"] }
tower = { version = "0.4.13", features = ["make"], optional = true }

# Tide does not have tokio support. So make sure async-std is compatible with tokio
# https://github.com/http-rs/tide/issues/791
[dependencies.async-std]
version = "1.12.0"
features = ["tokio1"]

[dependencies.shuttle-codegen]
version = "0.5.1"
path = "../codegen"
optional = true

[dev-dependencies]
portpicker = "0.1.1"
uuid = { version = "1.1.2", features = ["v4"] }

[dependencies.shuttle-common]
version = "0.5.1"
path = "../common"

[features]
default = ["codegen"]
codegen = ["shuttle-codegen"]
loader = ["cargo", "libloading"]

sqlx-integration = ["sqlx/runtime-tokio-native-tls"]
sqlx-postgres = ["sqlx-integration", "sqlx/postgres"]
sqlx-aws-postgres = ["sqlx-integration", "sqlx/postgres"]
sqlx-aws-mysql = ["sqlx-integration", "sqlx/mysql"]
sqlx-aws-mariadb = ["sqlx-integration", "sqlx/mysql"]

mongodb-integration = ["mongodb"]
secrets = ["sqlx-postgres"]

web-axum = ["axum", "sync_wrapper"]
web-rocket = ["rocket"]
web-tide = ["tide"]
web-tower = ["tower", "hyper"]
web-poem = ["poem"]
web-frenezulo_beta = ["frenezulo_beta"]

bot-serenity = ["serenity"]
